jog_joint_node:
  joint_names:
    - MFRAME
    - BLOCK
    - BOOM
    - ARM
    - TOHKU_PITCH
    - TOHKU_ROLL
    - UFRAME
    - MNP_SWING
    - MANIBOOM
    - MANIARM
    - MANIELBOW
    - YAWJOINT
    - HANDBASE
    - TOHKU_TIP_01
    - TOHKU_TIP_02
    - PUSHROD
jog_frame_node:
  group_names:
    - tohoku_arm
    - mani_arm
  link_names:
    - TOHKU_ROLL
    - HANDBASE
